stages:
    - build
    - deploy

variables:
    SSH_PATH: /tmp/ssh_key.pem
    DOCKER_IMAGE_NAME: csmlog-backend-dev
    DOCKER_IMAGE_TAG: $CI_COMMIT_TAG
    DOCKER_PUSH_NAME:  $REGISTRY_USER/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
.build:
    stage: build
    image: docker:23.0-cli
    services:
        - docker:dind
    variables:
        DOCKER_TLS_CERTDIR: '/certs'
    before_script:
        # login docker hub
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        # define .env ( create file .env in image )
        - cat $env > .env

        - echo $REGISTRY_USER
        - echo $CI_COMMIT_REF_NAME
        - echo $REGISTRY_USER:$CI_COMMIT_REF_NAME
        # build and push image
        - docker build --platform linux/amd64 -t $DOCKER_PUSH_NAME .
        - docker push $DOCKER_PUSH_NAME
        - docker rmi -f $DOCKER_PUSH_NAME

build-dev:
    extends: .build
    #Push #ENV_DEV:config to env:image
    variables:
        env: $ENV_DEV
    only:
        - tags
        - /^dev-.*$/

deploy-dev:
    stage: deploy
    only:
        - tags
        - /^dev-.*$/
    before_script:
        # move ssh from vairable (gitlab) to SSH_PATH
        - echo "$SSH" > $SSH_PATH
        # change mod
        - chmod 600 $SSH_PATH
        - chmod 400 $SSH_PATH
    script:
        # Change image tags
        - ssh -o StrictHostKeyChecking=no -i $SSH_PATH $USER_SERVER@$IP_SERVER "cd product/application &&  sudo sed -i "s/$DOCKER_IMAGE_NAME:.*/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG/" docker-compose.yml && docker-compose up -d "